version: "3.8"

services:
  web-service:
    build: .
    ports:
      - "5001:80"
    logging:
      driver: fluentd
  posgres:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ServiceTemplate
    volumes:
      - "./var/lib/postgresql/data:/var/lib/postgresql/data"